
image: docker:20
stages:
  - test_and_build
  - docker_build
  - system_test
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

test:
  image: docker:19.03.1
  services:
    - docker:19.03.1-dind
  stage: test_and_build
  script:
    - apk add --no-cache bash
    - bash ci/unit-test-app.sh
build:
  stage: test_and_build
  services:
    - docker:20-dind
  script:
   - apk add --no-cache bash
   - chmod +x ci/build-app.sh && ci/build-app.sh
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      -  .
docker_build:
    image: docker:19.03.1
    stage: docker_build
    cache:
      key: "$CI_COMMIT_REF_NAME"
      paths:
        - .
    services:
    - docker:19.03.1-dind
    script:
      - apk add --no-cache bash
      - bash ci/lint-dockerfile.sh
      - chmod +x ci/build-docker.sh && export GIT_COMMIT="GL-$CI_COMMIT_SHA" && ci/build-docker.sh
      - chmod +x ci/push-docker.sh  && export GIT_COMMIT="GL-$CI_COMMIT_SHA" && ci/push-docker.sh
system_test:
    image: docker/compose
    stage: system_test
    cache:
      key: "$CI_COMMIT_REF_NAME"
      paths:
        - .
    services:
    - docker:19.03.1-dind
    script: 
    - apk add --no-cache bash
    - chmod +x ci/component-test.sh  && export GIT_COMMIT="GL-$CI_COMMIT_SHA" && ci/component-test.sh
    - export GIT_COMMIT="GL-$CI_COMMIT_SHA" && ci/performance-test.sh