
image: docker:20
stages:
  - test_and_build
  - docker_build
  - component_test
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

build:
  stage: test_and_build
  script: echo executing from "$PWD" && ls && chmod +x ci/unit-test-app.sh && ci/unit-test-app.sh
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - .
test:
  stage: test_and_build
  script: chmod +x ci/build-app.sh && ci/build-app.sh
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      -  .
docker_build:
    image: docker:19.03.1
    stage: docker_build
    cache:
      key: "$CI_COMMIT_REF_NAME"
      paths:
        - .
    services:
    - docker:19.03.1-dind
    script:
      - apk add --no-cache bash
      - chmod +x ci/build-docker.sh && export GIT_COMMIT="GL-$CI_COMMIT_SHA" && ci/build-docker.sh
      - chmod +x ci/push-docker.sh  && export GIT_COMMIT="GL-$CI_COMMIT_SHA" && ci/push-docker.sh
component_test:
    image: docker/compose
    stage: component_test
    cache:
      key: "$CI_COMMIT_REF_NAME"
      paths:
        - .
    services:
    - docker:19.03.1-dind
    script: 
    - apk add --no-cache bash
    - chmod +x ci/component-test.sh  && export GIT_COMMIT="GL-$CI_COMMIT_SHA" && ci/component-test.sh