version: 2
jobs:
  clone:
    docker:
      - image: alpine
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    machine:
      image: ubuntu-2004:current
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Test with gradle
          command: bash ci/unit-test-app.sh

  build:
    machine:
      image: ubuntu-2004:current
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Build with gradle
          command: bash ci/build-app.sh
      - persist_to_workspace:
          root: .
          paths:
            - .
  Docker-image:
    machine: 
      image: ubuntu-2004:current
    steps:
      - attach_workspace:
          at: .
      - run:
          name: lint docker
          command: bash ci/lint-dockerfile.sh
      - run:
          name: build docker
          command: export GIT_COMMIT="CC-$CIRCLE_SHA1" && bash ci/build-docker.sh
      - run:
          name: push docker
          command: export GIT_COMMIT="CC-$CIRCLE_SHA1" && bash ci/push-docker.sh
  system-test:
    machine: 
      image: ubuntu-2004:current
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Execute component test
          command: export GIT_COMMIT="CC-$CIRCLE_SHA1" && bash ci/component-test.sh
      - run:
          name: Execute performance test
          command: export GIT_COMMIT="CC-$CIRCLE_SHA1" && bash ci/performance-test.sh

workflows:
  version: 2
  the_flow:
    jobs:
      - clone
      - test:
          requires:
            - clone
      - build:
          requires:
            - clone
      - Docker-image:
          requires:
            - build
      - system-test:
          requires:
            - Docker-image