name: Java CI

on: [push]
env: # Set the secret as an input
  docker_username: ${{ secrets. docker_username }}
  docker_password: ${{ secrets. docker_password }}
jobs:
  Clone-down:
    name: Clone down repo
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build with Gradle
      run:  chmod +x ci/build-app.sh && ci/build-app.sh
    - name: Upload Repo
      uses: actions/upload-artifact@v1
      with:
        name: code
        path: .
  Test:
      runs-on: ubuntu-latest
      needs: [Clone-down]
      steps:
      - name: Download code
        uses: actions/download-artifact@v1
        with:
          name: code
          path: .
      - name: Test with Gradle
        run: chmod +x ci/unit-test-app.sh && ci/unit-test-app.sh
  Build:
      runs-on: ubuntu-latest
      needs: [Clone-down]
      steps:
      - name: Download code
        uses: actions/download-artifact@v1
        with:
          name: code
          path: .
      - name: Build with Gradle
        run:  chmod +x ci/build-app.sh && ci/build-app.sh
      - name: Upload Repo
        uses: actions/upload-artifact@v1
        with:
          name: code
          path: .
  Docker-image:
    runs-on: [ubuntu-latest]
    needs: [Build,Test]
    steps:
    - name: Download code
      uses: actions/download-artifact@v1
      with:
        name: code
        path: .
    - name: lint dockerfile
      run: bash ci/lint-dockerfile.sh
    - name: build docker
      run: export GIT_COMMIT="GA-$GITHUB_SHA" && ci/build-docker.sh
    - name: push docker
      run: export GIT_COMMIT="GA-$GITHUB_SHA" && ci/push-docker.sh
  System-test:
    runs-on: [ubuntu-latest]
    needs: [Docker-image]
    steps:
    - name: Download code
      uses: actions/download-artifact@v1
      with:
        name: code
        path: .
    - name: Execute component test
      run: GIT_COMMIT="GA-$GITHUB_SHA" && ci/component-test.sh
    - name: Execute performance test
      run: GIT_COMMIT="GA-$GITHUB_SHA" && ci/performance-test.sh
